apiVersion: v1
kind: Pod
metadata:
  name: posgres-db-pod
  labels:
    name: posgres-db-pod
    app: example-voting-app
spec:
  containers:
    - name: db
      image: postgres:9.4
      ports:
        - containerPort: 5432