apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: db-service
    app: example-voting-app
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: posgres-db-pod
    app: example-voting-app
  type: ClusterIP
