apiVersion: v1
kind: Pod
metadata:
  name: postgres-db-pod
  labels:
    name: postgres-db-pod
    app: example-voting-app
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432