apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: example-voting-app
spec:
  containers:
    - name: worker
      image: dockersamples/examplevotingapp_worker